apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
   app: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
     labels:
      app: addressbook
    spec:
      containers:
      - name: addressbook
        image: yamini0727/war_test_docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
