---                                                                                                                     
apiVersion: v1                                                                                                          
kind: Service                                                                                                          
metadata:                                                                                                                 
  name: addressbook
  namespace: default
  labels:
    app: addressbook  
spec:                                                                                                                     
  ports:
   - name: http          
     port: 8080                                                                                                                                                          
     protocol: TCP
     targetPort: 8080     
  selector:                                                                                                                
    app: addressbook
  type: LoadBalancer
  externalIPs:
  - 54.237.90.47 
